name: test and deploy to dev 

on: 
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test_iris_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Verify uv installation
        run: uv --version
      
      - name: Install uv iris api env
        run: |
          cd iris_api
          uv run pytest test.py
